### ISSUE TITLE
Create a grunt task that fixes all the names

### ISSUE THREAD

**Issue by samreid** [phetsims/simula-rasa#1]
We should create a grunt task that is run with the name of the simulation, and the names of the screens (if more than one), and it uses the simula-rasa as a template for updating the filenames, vars, etc.

**Comment by pixelzoom** [comment]
@samreid can we close this?  `grunt create-sim` does what was requested here, with the exception of multiple screens, and it seems to be serving us well.  And the request for multiple screens is tracked in #19.

**Comment by samreid** [comment]
Yes, I think this issue can be closed, thanks!
