### ISSUE TITLE
values entered on keypad don't fix in boxes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/simula-rasa#11]
It's possible to enter numbers on the keypad that don't fit in the boxes used to display those values. Examples:

Shopping screen, value entered is "9999":

![screenshot_35](https://cloud.githubusercontent.com/assets/3046552/19053590/cc9725fa-8978-11e6-97a6-bc31bc0ce71f.png)

Shopping screen, value entered is "5555":

![screenshot_34](https://cloud.githubusercontent.com/assets/3046552/19053564/b45e5436-8978-11e6-8b4f-1ac6580172da.png)

@arouinfar Please decide how to proceed.

**Comment by arouinfar** [comment]
@pixelzoom let's increase the width of all text boxes by a few pixels to accommodate the strings from your examples. The padding can be pretty tight --1px of empty space between the edge of the text (at max length) and the box seems appropriate. For example, the padding in this screenshot looks about right.
![image](https://cloud.githubusercontent.com/assets/8419308/19057775/8e161fb8-898f-11e6-8c8a-2a1ac31d63f8.png)

**Comment by arouinfar** [comment]
By the way should this issue be in the unit-rates repo @pixelzoom?

**Comment by pixelzoom** [comment]
Indeed, wrong repo. Moved to https://github.com/phetsims/unit-rates/issues/102, closing.
