### ISSUE TITLE
Consider changing initial version to 1.0.0-dev.0

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/simula-rasa#13]
Since chipper 2.0's `grunt dev` auto-increments the version, it ends up with dev.2 being the first thing deployed currently (ran into this with area-model-counting).

We do something similar when we create release branches, so that incrementing dev versions works nicely. Thus the documentation in our pre-chipper-2.0 checklist:

> Update the version id in package.json for master. Master should be set up for what would be the next release branch name. So if you just created release branch 1.3, then the version should be "1.4.0-dev.0" in master. (Note the "0" for the dev number, so that grunt bump-version works properly.)

Thoughts/objections?

**Comment by pixelzoom** [comment]
+1 for changing to "1.0.0-dev.0".

**Comment by samreid** [comment]
Yes, dev.0 seems like the right start version.

**Comment by pixelzoom** [comment]
1/18/18 dev meeting: No objection, @jonathanolson will make the change.

**Comment by jonathanolson** [comment]
Done.
