### ISSUE TITLE
add PhET-iO instrumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/simula-rasa#14]
This came up in a Slack discussion with @ariel-phet.  The simula-rasa sim templated should at some point be modified to include boilerplate PhET-iO instrumentation for main.js, top-level model/view classes, etc.

**Comment by jessegreenberg** [comment]
@chrisklus is going to instrument this, after discussion in 10/11/18 dev meeting.

**Comment by pixelzoom** [comment]
@chrisklus please review #14 before doing this. 

For the top-level classes (Screen subclass, ScreenView subclass, model) the `tandem` should be passed as a required constructor parameter, not via options.

**Comment by pixelzoom** [comment]
@chrisklus If you need someone to review when you're done with this, please assign to me.

**Comment by chrisklus** [comment]
@samreid and I did this yesterday and then created a new phet-io sim with instrumented Simula Rasa, and all worked well. I don't think a review is needed.

Ready to close if you are @pixelzoom.
