### ISSUE TITLE
port to ES6

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/simula-rasa#15]
Since new sim development will be done in ES6, simula-rasa should be ported to ES6.  We could either do this proactively, or the next person who needs to create a new sim repo could do it.

**Comment by jessegreenberg** [comment]
No objections! Thanks @pixelzoom

**Comment by pixelzoom** [comment]
ES6 port completed.  Testing:
- ran simula-rasa in requirejs mode
- ran `grunt create-sim` and tested the resulting sim in requirejs mode
- inspect .js files created by `grunt create-sim`

@chrisklus please review this before doing #14.

**Comment by chrisklus** [comment]
@samreid and I reviewed - looks really nice. We are going to start on #14.
