### ISSUE TITLE
'grunt create-sim' sets incorrect version in package.json 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/simula-rasa#16]
After running `grunt create-sim`, the version in package.json is:

```
"version": "1.0.0-dev.1",
```

Since version number is auto-incremented by `grunt dev`, this should be `1.0.0-dev.0`.   I've been manually correcting this, but will track it down.

**Comment by pixelzoom** [comment]
I corrected the version id in simula-rasa/package.json.

Assigning to @ariel-phet to have someone review.

**Comment by ariel-phet** [comment]
@Denz1994 said he can look at this.

**Comment by Denz1994** [comment]
This was tested by running:
`grunt create-sim --repo=simula-rasa--author="Denzell Barnett (PhET Interactive Simulations)"`
`grunt create-sim --repo=test-sim --author="Denzell Barnett (PhET Interactive Simulations)"`

Both commands produced a `package.json` starting at `1.0.0-dev.0`. 

The first command proves this was resolved. The second was a sanity check to make sure this wasn't sim specific. 

This looks good. Turning back over to @pixelzoom.

**Comment by pixelzoom** [comment]
Thanks @Denz1994, closing.
