### ISSUE TITLE
port simula-rasa_en.html to use ES6

### ISSUE THREAD

**Issue by veillette** [phetsims/simula-rasa#17]
all the .js modules of simula-rasa have been ported to ES6, but there are a few vars remaining in the html file.

**Comment by samreid** [comment]
According to https://caniuse.com/#feat=const and since we only support IE11+, it seems safe to use `const` in non-transpiled files.  We could potentially change this in several files in chipper/templates/*

**Comment by samreid** [comment]
I volunteered to look into this.

**Comment by samreid** [comment]
I asked if I should also convert to arrow functions.  We think that will work but other developers will report back if they are no longer able to test in requirejs on a platform they would otherwise expect to.

**Comment by samreid** [comment]
Also, I discovered that `let` and `const` are block-level scoped (unlike vars which got promoted to `window`), so we can remove the IIFE.

**Comment by samreid** [comment]
I ported the development template to use ES6, including let, const and arrow functions, and removed the extraneous IIFE.  I also updated the formatting to use the IDEA style indenting.  @ariel-phet can you please suggest a reviewer to take a look (should be <10 minutes) before we `grunt update` and commit across all of our repos?

**Comment by ariel-phet** [comment]
@veillette seems like a great choice

**Comment by veillette** [comment]
I reviewed the change and ran locally grunt update and  tested it using vector addition. The simulation runs on require-js and builds properly using chrome. In addition, the build version of vector-addition works on IE11. 

However, i found out that it doesn't work on IE11 with requirejs. 

Digging further in, I found that even without the ES6 change that was submitted above to the html file,  (I used  area-builder as a testing ground) the simulation doesn't run on IE11 in requirejs mode. I'm unaware if this is known and not considered a problem at this point. 

![image](https://user-images.githubusercontent.com/7633344/59478216-8f902200-8e26-11e9-8047-c8466fed9369.png)


I'm reassigning to @samreid to decide on how to proceed at this point.

**Comment by samreid** [comment]
It is a known problem that IE11 requirejs hasn't been working since we upgraded to ES6.  During today's developer meeting, we recalled this and agreed it should not prevent us from moving forward here.  I'll run `grunt update` everywhere to pick up these changes.

**Comment by samreid** [comment]
Local testing is clear.  I ran `for-each.sh perennial/data/active-runnables grunt update` and pushed to master.  Leaving open until we see results from CT.

**Comment by veillette** [comment]
This passes CT. Closing.
