### ISSUE TITLE
simulaRasaColors should be capitalized

### ISSUE THREAD

**Issue by samreid** [phetsims/simula-rasa#20]
From discussion with @pixelzoom, we would like to capitalize this colors file.  I updated the code review checklist, but simula-rasa still needs to change.

**Comment by pixelzoom** [comment]
I'll do this.

**Comment by pixelzoom** [comment]
Done in the above commits, tested with `grunt create-sim --repo=foo --author=CM --title="Foo"`.


There are 2 commits because I've experience problems when just changing case.  So the rename had an intermediate step: simulaRasaColors.js -> simulaRasaColors1.js -> SimulaRasaColors.js

**Comment by marlitas** [comment]
@samreid and I discovered that the filename for `SimulaRasaColors` is pascal-case, but the export and variable are camel-case:

```js
const simulaRasaColors = { 
...
export default simulaRasaColors;
```

These should be pascal-case as well.

**Comment by marlitas** [comment]
Completed. Closing.
