### ISSUE TITLE
SimulaRasaQueryParameters are not used

### ISSUE THREAD

**Issue by samreid** [phetsims/simula-rasa#24]
@marlitas and I noticed this code in SimulaRasaQueryParameters:
```
logGlobal( 'phet.chipper.queryParameters' );
logGlobal( 'phet.preloads.phetio.queryParameters' );
logGlobal( 'phet.simulaRasa.SimulaRasaQueryParameters' );
```

And this comment:

```ts
/**
 * Defines query parameters that are specific to this simulation.
 * Run with ?log to print query parameters and their values to the browser console at startup.
```

However, we were surprised that running the sim with ?log did not show anything in the log.  We discovered that SimulaRasaQueryParameters has no usages and is hence not being loaded.  Should it be loaded by something on startup?

Assigning to @pixelzoom since he is listed as the responsible dev.  Please reassign accordingly as appropriate.

**Comment by pixelzoom** [comment]
I don't think any change here is necessary or desirable.  This is a "temporary" workaround until https://github.com/phetsims/query-string-machine/issues/46 (and perhaps) https://github.com/phetsims/chipper/issues/1002) are addressed.

Longterm, SimulaRasaQueryParameters certainly shouldn't be responsible for logging `phet.chipper.queryParameters` and `phet.preloads.phetio.queryParameters`.   QueryStringMachine should ideally be responsible for logging.   But what that looks like is unknown until the above issues are addressed. 

In the meantime, if the current logging bothers you, or if you think it should not be part of the templated, feel free to remove it from SimulaRasaQueryParameters.

**Comment by samreid** [comment]
I wasn't concerned about the logging at all, but that more led us to the realization that the file SimulaRasaQueryParameters is not used at all, so that code is never running.  Is that by design?  If so, please feel free to close the issue.

**Comment by pixelzoom** [comment]
It's not by design. 

I tried adding an unused `import` to simula-rasa-main.ts:

```js
import simulaRasaStrings from './simulaRasaStrings.js';

//TODO delete this line after you've added sim-specific query parameters to SimulaRasaQueryParameters
import SimulaRasaQueryParameters from './common/SimulaRasaQueryParameters.js'; // eslint-disable-line

const simulaRasaTitleString = simulaRasaStrings[ 'simula-rasa' ].title;
```

But transpile.js really messes that up. It strips out the import, moves the TODO to the previous line, and (yikes!) moves the `// eslint-disable-line` to the next line:

```js
import simulaRasaStrings from './simulaRasaStrings.js'; //TODO delete this line after you've added sim-specific query parameters to SimulaRasaQueryParameters

// eslint-disable-line
const simulaRasaTitleString = simulaRasaStrings['simula-rasa'].title;
```

**Comment by samreid** [comment]
I can understand that babel doesn't guarantee whitespace changes, and it seems reasonable that babel strips out unused imports.  Should we add an example usage of SimulaRasaQueryParameters so its import is not stripped out?

**Comment by pixelzoom** [comment]
I started adding an example, like this (uncommitted):

```js
// SimulaRasaQueryParameters.ts

  //TODO This is an example, delete it before publishing
  sayHello: {
    type: 'flag'
  }

// simula-rasa-main.ts

  //TODO This is an example of how to use a query parameter. Delete before publishing.
  if ( SimulaRasaQueryParameters.sayHello ) {
    console.log( 'Hello' );
  }
```

But I'm really not going to appreciate having to remove this example.  And I'm guessing there will be similar feedback from other devs.

@samreid thoughts?

**Comment by samreid** [comment]
How about adding an import like this to simula-rasa-main?

```ts
import './common/SimulaRasaQueryParameters.js';
```

**Comment by samreid** [comment]
Which of the problems identified in https://github.com/phetsims/simula-rasa/issues/24#issuecomment-1104237264

```ts
//TODO delete this line after you've added sim-specific query parameters to SimulaRasaQueryParameters
import SimulaRasaQueryParameters from './common/SimulaRasaQueryParameters.js'; // eslint-disable-line
```

are also exhibited in https://github.com/phetsims/simula-rasa/issues/24#issuecomment-1123183084 ?

```ts
import './common/SimulaRasaQueryParameters.js';
```

**Comment by pixelzoom** [comment]
If that indeed work, feel free to add it.  I'm generally responsible for the repo, but not for all aspects of simula-rasa.   And I don't feel strongly about whether this is necessary or not.

**Comment by pixelzoom** [comment]
Should there be a comment about why that import is necessary, and that it should be removed after the sim developer uses their {{REPO}}QueryParameters.ts file elsewhere?

**Comment by pixelzoom** [comment]
Should there be a code comment (TODO) about why that import is necessary, and that it should be removed after the sim developer uses their {{REPO}}QueryParameters.ts file elsewhere?

**Comment by samreid** [comment]
Those steps don't seem necessary to me, if that seems preferable to you I'm happy to add it.

**Comment by pixelzoom** [comment]
I predict questions about why every main.ts has an import for something that it doesn't use. But let's wait and see.

**Comment by pixelzoom** [comment]
I predict questions (or code-review issues) about why every main.ts has an import for something that it doesn't use. But let's wait and see.
