### ISSUE TITLE
Typo in SimulaRasaColors.ts

### ISSUE THREAD

**Issue by marlitas** [phetsims/simula-rasa#25]
There's a typo in the comment describing background colors: 
```// Background color that for screens in this sim```

Would recommend removing "that" so the comment reads:
```// Background color for screens in this sim```

**Comment by marlitas** [comment]
@samreid tried to push up commit with change but received this error from Center and Variability: 
```Permission to phetsims/center-and-variability.git denied to marlitas.```

**Comment by samreid** [comment]
I updated the settings, can you please retry?
