### ISSUE TITLE
New sims will not transpile until added to perennial-alias/data/active-repos

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/simula-rasa#28]
I recently used steps in the simula-rasa readme to create a sim and it wouldn't run until I added the new sim to perennial-alias/data/active-repos. I added some notes to the README what to do to transpile the sim. @samreid can you please review, does that seem OK?

**Comment by samreid** [comment]
Looks great, thanks.  I also fixed one typo.  Closing.

**Comment by pixelzoom** [comment]
Wait... Is this incompleted? Doesn't a new TS sim also need to be added to chipper/tsconfig/all/tsconfig.json?

**Comment by samreid** [comment]
That step is listed in the new repo checklist: https://github.com/phetsims/phet-info/blob/6e0ecefe5a370f4cfca3d3f7932ec53bea028fd2/checklists/new-repo-checklist.md

**Comment by pixelzoom** [comment]
> But I don't see a way for 3rd parties to leverage that unless they fork chipper

But isn't an entry in chipper/tsconfig/all/tsconfig.json required for transpilation and lint to work correctly?

**Comment by jessegreenberg** [comment]
I think better to point to existing documentation than duplicate, I updated the README again. That way it points to adding the new repo to tsconfig.json.

> I don't see a way for 3rd parties to leverage that unless they fork chipper

absolute-tsc lets you point to a different config, maybe we have one ready for 3rd parties? We will need a different setup for lint.

**Comment by samreid** [comment]
Right, 3rd parties can just `tsc` from their `my-sim/` directory, which will correctly traverse dependencies for type checking. But for linting, .eslintrc points to all/tsconfig which will not list the client sim.  It would be best for clients to be able to use our lint rules.  But I don't know a good solution to that problem based on the nature of all/tsconfig.  I think we should create an "type:open-source-ecosystem" issue label so we can track things like this.

**Comment by samreid** [comment]
I recommend we closes this and continue in https://github.com/phetsims/chipper/issues/1351
