### ISSUE TITLE
Generated sim doesn't launch

### ISSUE THREAD

**Issue by jbphet** [phetsims/simula-rasa#3]
While using simula-rasa to generate the framework for the gene-expression-basics sim, I found that the generated code doesn't launch.  It appears that simula-rasa hasn't been updated to reflect some of the recent changes to PhET's practices, specifically some of the recent changes to chipper.

The changes that were made in order to get gene-expression-basics to launch could probably serve as a list of the things that need to be updated.  See https://github.com/phetsims/gene-expression-basics/commit/212a324c0ed44bc6743188aabd8c4b86b0b51a5b.

**Comment by pixelzoom** [comment]
@jbphet is this still an issue?

**Comment by pixelzoom** [comment]
I just tested using `grunt create-sim` and the result runs fine. Closing.
