### ISSUE TITLE
Rename images/README.txt to images/README.md

### ISSUE THREAD

**Issue by samreid** [phetsims/simula-rasa#6]
I noticed that the README is a txt instead of md and thought md would make more sense.

**Comment by pixelzoom** [comment]
Existing image/README.txt in sim repos should also be renamed.

**Comment by samreid** [comment]
I see only one occurrence of images/README.txt in a simulation and it is in projectile-motion.  I think we (I?) decided to delete these instead of proliferate them.

**Comment by samreid** [comment]
Done in https://github.com/phetsims/chipper/issues/190.  @pixelzoom anything else to do here?
